### ISSUE TITLE
Failed to connect to Interface

### ISSUE THREAD

**Issue by unnui** [battlecoder/zeppp#11]
Hello! I'm getting this error and I'm not even sure why.
This is all the CLI log I get.
I'm using x86-64 Linux, but I doubt it has anything to do with this error.

> $ sudo java -jar zeppp-cli.jar -c /dev/ttyACM0 -d 16f877a -i hello.hex -p

> Opening port /dev/ttyACM0...
> Connecting to ZEPPP interface...
> ERROR: Failed to Connect to interface. No response from interface

Already tested changing ports and building the .jar myself, but nothing seems to work.

**Comment by battlecoder** [comment]
Hi unnui!
Can you try with -wait 2000 after your port string ? Depending on the Arduino you are using you may need to tell ZEPPP to wait 2 seconds before sending any command. Let me know if that works.

Regards,

**Comment by unnui** [comment]
Hello again!
No, sadly it outputs the same results. I've checked every pin is connected fine. I'm not sure what the interface problem here is. My MC is a PIC16F877A, and I can mostly assure it works fine. Thank you for your quick reply!

**Comment by battlecoder** [comment]
Hi!
What Arduino board are you using? Are you sure that /dev/ttyACM0 is the port where it's connected?

**Comment by unnui** [comment]
I found out what was wrong! Somehow I ignored a compilation error from the ZEPP_icsp.h file.
The line
> #include <arduino.h>
seems to output a compilation error in the Arduino IDE: `No such file or directory`. It was an easy fix, just changing it to
> #include <Arduino.h>
made the trick.
Btw, I'm using an Arduino UNO. Thank you so much for your help anyways!
