### ISSUE TITLE
ERROR: Failed to Detect connected device. Unrecognized device with ID 0x0000

### ISSUE THREAD

**Issue by Koocy** [battlecoder/zeppp#14]
using the latest version of zeppp on a chinese Arduino UNO clone and a PIC16F628A.

java -jar zeppp-cli.jar -c COM5 -wait 3000 -i MPLABXProjects.production.hex -p
Opening port COM5...
Waiting 3000 ms ...
Connecting to ZEPPP interface...
-- Interface detected: ZEPPP 1.0.2 20220824
Detecting connected device...
ERROR: Failed to Detect connected device. Unrecognized device with ID 0x0000

**Comment by battlecoder** [comment]
Hi,  here's a quick checklist of things to verify:
- Please double check the connections between the PIC and the Arduino.
- Is the Arduino ground connected to your PIC's ground?
- Is the PIC receiving power (i.e: Are all its Vdd/Vcc and GND pins connected to a power supply? The programmer does not provide power to the PIC, although you could connect the Arduino's 5V pin to your PIC if it's not going to draw much current)

Additional question: Is that a brand new IC or has it used before (and thus it could be defective, burnt, or might have LVP disabled)

**Comment by Koocy** [comment]
hi. I just tried it with a unused PIC16F628A and the GND pin of Arduino Uno is connected to the Vss pin of PIC but still the same thing

**Comment by battlecoder** [comment]
Can you please describe all the connections you have between the Arduino and the PIC? Thanks

**Comment by battlecoder** [comment]
@Koocy Did you manage to find the problem with your setup? I'll be closing this issue in a couple of days, unless you require further assistance. Let me know.
