### ISSUE TITLE
What about PIC16F636

### ISSUE THREAD

**Issue by ortegafernando** [battlecoder/zeppp#5]
Hi, do you think I could use this zeppp solution with an PIC16F636 ?

My garaje door remote control is not working (even changing battery. May be low battery has corrupted the PIC), but my wife's remote control is working well. I want to read it and write to my remote control.

What do you think?

Thanks.

**Comment by battlecoder** [comment]
Hi!
I definitely want to add support for more microcontrollers, so I'm always happy to hear people asking for specific devices.
Now, I'm not familiar with the PIC16F636, but I just checked its datasheet and memory programming specifications, and it apparently doesn't support low voltage programming (LVP), which is what ZEPPP employs. It's a "HVP-only" device.

Sorry :/
