### ISSUE TITLE
Support for PIC16F627-20/P

### ISSUE THREAD

**Issue by maltalef101** [battlecoder/zeppp#8]
It's basically the same as a 16F627A but clocked at 20 mHz.

Using Arduino UNO R3, here's a pic of  my setup:
![image](https://user-images.githubusercontent.com/64824522/183273478-5ce71c8c-4b9c-4711-83b7-ede1ffae6d84.png)

This is the error I get if I set the `-d` flag to `16f627a`.
```bash
$ java -jar zeppp-cli.jar -c /dev/ttyACM0 -wait 2500 -d 16f627a -ra -o dump.hex
Waiting 2500 ms ...
Connecting to ZEPPP interface...
-- Interface detected: ZEPPP 1.0.1 20200715
Pic device '16f627a' selected
Detecting connected device...
ERROR: Failed to Detect connected device. Unrecognized device with ID 0x07a0
```
ID `0x07a0` is, from what information I've been able to gather, the correct ID for the PIC I have.

I've given it my own shot at implementing it but I've had no success.

**Comment by battlecoder** [comment]
Hi @maltalef101 
Thanks for bringing this to my attention!
It looks like **ZEPPP** is reading the ID correctly, so it's able to communicate with the device.
I was under the impression that the non-A 62X devices didn't support LVP, and thus couldn't work with ZEPPP. However, they seem to support it, according to their datasheet.
I was already working on an experimental branch with other devices but I added the 627 and 628 (non-A) to a sub-branch of it. Can you switch to the ["with-PIC16F62X" branch](https://github.com/battlecoder/zeppp/tree/experimental/with-PIC16F62X) and try it? I updated the **zeppp-cli.jar** on that branch too, so no manual re-compiling needed.

If you can try all operations (read, write, verify) for both eeprom and program data I would really appreciate it, as I don't have non-A 627 or 628 devices at hand.

Thanks, and please let me know if that version works!

**Comment by maltalef101** [comment]
Thank you very much for the fast response.

In other news, it works!

Thank you!

**Comment by battlecoder** [comment]
That's fantastic! I'm really glad to hear that!

Could you please provide some more details regarding what you managed to test? Before considering this issue fully closed (and preparing the experimental branch for merging into the main release) I'd love to know what functionality was tested.
Thanks in advance.
